# .github/workflows/docker-build-on-push.yml

name: Docker Build

on:
    push:
        branches:
            - 'create-ws*'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Docker Login
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build Docker Image
              uses: docker/build-push-action@v5
              with:
                  context: ./services/terms-teeft
                  file: ./services/terms-teeft/Dockerfile
                  push: true
                  tags: parmentf/teeft:latest
