# .github/workflows/docker-build-on-tag.yml

name: Docker Build & Push

on:
    push:
        tags:
            - '*@*'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout from Git
              uses: actions/checkout@v4

            - name: Docker Login
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Build & Push Docker Image
              shell: bash
              run: |
                  # See https://stackoverflow.com/questions/63745613/how-to-get-a-branch-name-on-github-action-when-push-on-a-tag
                  raw=$(git branch -r --contains ${{ github.ref }})
                  branch=${raw/origin\/}
                  echo "Building and pushing image for ${{ github.ref_name }} ($branch)"
                  bin/build-and-push.sh $branch
