# .github/workflows/docker-build-on-push.yml

name: Docker Build & Test

on:
    push:
        branches:
            - '*/major/*'
            - '*/minor/*'
            - '*/patch/*'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout from Git
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Docker Login
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Install Hurl
              run: |
                  curl --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/4.1.0/hurl_4.1.0_amd64.deb
                  sudo dpkg -i hurl_4.1.0_amd64.deb
                  hurl --version

            - name: Build Docker Image & Test
              shell: bash
              run: |
                  bin/build-and-test.sh
                  # docker push parmentf/teeft:latest
